# Generated by Django 3.1.7 on 2021-10-31 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha en la que fue creado el registro.', verbose_name='creado en')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha en la que fue modificado el registro.', verbose_name='mmodificado en')),
                ('name', models.CharField(max_length=140, verbose_name='Nombre del circulo')),
                ('slug_name', models.SlugField(max_length=40, unique=True)),
                ('about', models.CharField(max_length=250, verbose_name='Descripcion del circulo')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='circles/pictures')),
                ('rides_offered', models.PositiveBigIntegerField(default=0)),
                ('rides_taken', models.PositiveBigIntegerField(default=0)),
                ('verified', models.BooleanField(default=False, help_text='Circulo verificado por las autoridades', verbose_name='Circulo verificado')),
                ('public', models.BooleanField(default=True, help_text='Circulos publicos para que puedan ser visibles para todos los usuarios')),
                ('is_limit', models.BooleanField(default=False, help_text='Limitar un grupo unicamente para una cantidad establecidad de usuarios', verbose_name='Limitado')),
                ('member_limit', models.PositiveBigIntegerField(default=0, help_text='En el caso que el usuario sea limitado se establece la cantidad de usuarios que pueden ingresar')),
            ],
            options={
                'ordering': ['-rides_taken', '-rides_offered'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
